### ISSUE TITLE
Import and prepare EMEP deposition data

### ISSUE THREAD

**Issue by kariaust** [JamesSample/critical_loads_2#4]
EMEP deposition data are available as nine .NO files here: K:\Avdeling\317 Klima- og miljømodellering\KAU\Focal Centre\Projects\2016 Klassifiseringsprosjekt\Data\Deposisjon
They have a different format that the NILU data, as they are split on parameter/land cover rather than year. But just choose the best way to end up with similar deposition rasters as the other data. It is good if you can combine the NOx and ammonia data to total N on the way

Some explanation (for you, and to go with the data): 
The files are comma-separated ASCII-files of the form "P_LoLa_e.CC" with total depositions; where:
P=S,N,A: S,N,A stands for "Sulphur", "NOx" and "Ammonia", resp.;
e=a,f,v: a,f,v stands for "grid-average", "forests" and "semi-nat.vegie", resp.;
and CC=NO (for Norway ;-).
The depositions (in mgS|N/m2/a) are given in steps of 5 years between 1880 and 2010,
as well as for 2020 and 2030 under the GP-CLE scenario (version April 2013)
on the 0.50 x 0.25 deg Lon-Lat grid (given by its lower left, i.e. SW, corner).
S-depositions do not include SO4 from sea-salts.
The reference for the historic depositions is:
Schöpp W, Posch M, Mylona S, Johansson M (2003) Long-term development of acid
deposition (1880-2030) in sensitive freshwater regions in Europe.
Hydrology and Earth System Sciences 7(4): 436-446
1990 to 2010 is done with the (GAINS-)transfer matrices using country-emissions from IIASA; 2020 and 2030 are simulations with the EMEP model for the GP-CLE scenario (all reflecting the knowledge in July 2014)

Then - EMEP data are sometimes a bit off for Norway. So what we often do is to use the EMEP data just to find a change factor and then use this to calculate the future deposition for Norway. So in this case: I assume the EMEP and NILU data are on the same grid, whichever you choose. So, for each grid cell divide EMEP 2030 deposition by the EMEP 2010 deposition to get the change factor. Then multiply this by the NILU 2007-2011 deposition to give the estimated "NILU" 2030 deposition. Unless you have a more clever solution. But it does not have to be so sophisticated. I think rasterising the older deposition datasets are not yet part of the existing scripts, but this should be done in any case (for now doing it for 2007-2011 is sufficient. What I specifically need for the current exercise is to get deposition for S and N (total) for 2030 for "grid-average"

Put the hours on 11127 for now, but I hope there will be budget left on 190246 so that you can move part of it there later. I will let you know

Nothing urgent, but sooner rather than later. Within this month would be good

**Comment by JamesSample** [comment]
Closed by a9a3e74efeed367e9720f59131e4c056ad5379a5.

The notebook [here](https://nbviewer.jupyter.org/github/JamesSample/critical_loads_2/blob/master/notebooks/02b_add_emep_dep.ipynb) describes processing and uploading the EMEP data; the notebook [here](https://nbviewer.jupyter.org/github/JamesSample/critical_loads_2/blob/master/notebooks/02_deposition_new_grid.ipynb) shows how to extract & rasterise data for any historic data series and demonstrates "bias correcting" EMEP predictions for 2030 based on the NILU dataset (often called the "delta-change" method).

In particular, the functions `extract_deposition_as_gdf` and `create_deposition_raster` are now more generic, and should make it easier to access any deposition dataset of interest.

@kariaust Please have a look when you get chance and let me know if anything looks strange or needs further modification.
