### ISSUE TITLE
Critical loads and exceedances for Vestland

### ISSUE THREAD

**Issue by kariaust** [JamesSample/critical_loads_2#6]
This is related to the project on critical loads (water) and exceedances in Vestland, but it is also a good example for the need for a flexible system. What I would like to do is in short to calculate critical loads and exceedances for a range of sub-catchments, using dep data for 2012-2016 + 2030. This makes use of the calculate_critical_loads_for_water function, but in a different context than the recalc_water_cls notebook, so a separate notebook should be made – either for this specific project or a more general one (as you see fit). The stages needed:
1)	Changes to the calculate_critical_loads_for_water function: ‘BC0’ works only for the specific set of water chemistry data in the CL database (given per BLR), because they are from 1986, for which the regression is made. So here we would need to use ‘BC0_Ffac’. This means we need a third version of all the ANClimit and CL calculations. (this is more or less a copy-paste task, let me know if you want me to do it)
2)	Import shape files for sub-catchments: I store these on K. Not sure if you can import directly from there, or if you copy them to the CL database. Is shape file the desired format? Or does feature class work as well? I suppose you will rasterise them?
3)	Data for input_template_critical_loads_water.xlsx: Some of the input data would be easier to extract within the ‘system’, but I can also extract it externally, if time is limited. So these are just suggestions – let me know if you cannot do this.
a.	Nupt: Get N uptake from the BLR grid (CL database). If the sub-catchment is associated with different BLRs with different N uptake values, I think we should use the area-weighted average. 
b.	Catch_area: Calculate sub-catchment area from shapes (or from the attribute (arealEnh)
c.	Lake_area: Calculate lake area per sub-catchment from NVE_INNSJO map layer
d.	Forest_area: Calculate forest area per sub-catchment from AR50
e.	Runoff: Here I am not totally sure what to do yet. For sub-catchments with measured data I will use this. If they are in Hydra, they will be taken from there. Do you have a smart way to extract data from Hydra? In case I could e.g. provide the station code and the year range to average across (in the excel template)? Alternatively I will get it from Hydra myself. Where there are no measured data I wonder if we can use the HBV gridded data from Stein Beldring? Are we allowed to use it for other purposes than Elveovervåkingsprogrammet? He supplies the data per “Vassdragsområde”, right? So if we can use the data I could just supply the number for the “Vassdragsområde” and the year range to average across? Or again, if time is limited I can calculate the average myself – if I get the data. If we cannot use the HBV data I will simply use the 1961-1990 normal.
4)	Import excel template and calculate critical loads as in 2. in recalc_water_cls.ipynb.
5)	Calculate exceedances using both 2012-2016 (new method, new grid) and 2030 (see Issue #4) as in 4. in 04_water_new_grid.ipynb.
6)	Outputs:
a.	Table per catchment with absolute critical load (SSWC) and exceedances (SSWC and FAB, both time periods) for each sub-catchment (meq/m2/yr)
b.	Maps of critical load (SSWC) and exceedance (again four types) for each catchment, showing the different sub-catchments
c.	Potentially a nice actual map of the catchment, showing the sub-catchments, lakes and main river network (but if you don’t have time I can make this elsewhere)

Hours: O-10246

Deadline: It would be good to get this done as soon as possible (realising there is probably a pile of issues on your desk already), but the most urgent is to get some feedback on what you can or cannot do, so that I can plan for alternatives.

I will try to get a set of test data for one catchment as soon as possible, but I am waiting for feedback from Fylkesmannen

**Comment by kariaust** [comment]
Regarding 6 - exceedances. There should be only one exceedance value for each sub-catchment - to go into the table and to be plotted in the map. So if the deposition varies within the sub-catchment, an average value must be used

**Comment by JamesSample** [comment]
Hi @kariaust,

Some comments linked to your points above:

 1. For `BC0`, does it make sense for the user to select either `BC0` or `BC0_Ffac` when they call the `calculate_critical_loads_for_water` function (with the default to use `BC0`)? At present, I calculate both [here](https://github.com/JamesSample/critical_loads_2/blob/43e9b6398ad11983c8a968376487eed571f6165b/notebooks/critical_loads.py#L1169), but only the former gets used in subsequent calculations. I could change this so that the function uses whichever option the user specifies in the function call. What do you think? And am I right to assume the calculations for `BC0_magic` are the same regardless?

2. My broader "to do" list includes making generic `stations`, `projects` and `catchment_boundaries` tables in the DSToolkit database. I will then use these to store catchment boundaries for any stations (e.g. the 1000 Lakes catchments, your CL catchments, etc.), which will hopefully make it easy to access catchment data and intersect it with other spatial layers. **For each of your catchments, can you please send me**:

      - A `station_name` and `station_code` for the catchment outflow point

      - Geographic co-ordinates for the outflow (lat/lon or UTM - whichever you prefer)

      - A link/file path to the corresponding shapefile on the network for each station

   If the stations are already in e.g. RESA, you can use the same station names and codes from there for consistency, otherwise just choose whatever you think is sensible.

   Similarly, can you send me a `project_code` and `project_name` for this project, please (as above, you can use the RESA/AM project details if they exist already, otherwise just choose anything you like).

 3. Once I have the catchments in the database, most of these metrics should be easy to calculate from within the Toolkit. For runoff, unfortunately, Hydra-II does not have a nice API, so any data from there will need to be downloaded manually. The HBV data from Stein is only for the outflows of the major vassdragsområder, so if your catchments are small the HBV averages might be  misleading. seNorge has an API that allows downloading runoff for individual grid squares based on HBV, but I don't know if it's possible to query the gridded data directly. Might be worth checking to see if Jose has already looked into this?

Once all this is in place, I think (hope!) points 4 - 6 should be reasonably straightforward. As always, the main limitation will be time. Let's try to get 1 - 3 done first and see then see how much time I have left before baby chaos ;-)

**Comment by kariaust** [comment]
1) The three types of BC0 gives three types of outputs, in terms of ANC limits, CLs and exceedances. The only difference is that BC0_magic is a fixed number (for each grid cell, currently only available for BLR), while the other two are calculated based on BCt. I suggest it should be possible to select one, two or three of these. For instance in this project, there is no need for BC0_magic, while it could be useful to compare the two others

2) In this project part of the challenge is to define the sub-catchments. This depends largely on the availability of data - there is no point splitting into sub-catchments with no monitoring station representing them. So - I think the adding of catchment shapes and supporting data will have to be a bit flexible, that I can try out different ones. Is this possible within the setup you suggest?

Also, I do not really define the sub-catchments by a sampling point, but by different reaches of the river. Actually, some of them are not even true catchments. So far I have just used NVEs regine units, adding them up to give suitable sub-catchments. So I do not really have any coordinates. I can identify them in the map, of course, but are they actually needed in this context?

I am very far from defining all the sub-catchments, but I can supply what you need for one of the catchments, so that you can explore this further. I have made an overview in the excel file here: K:\Prosjekter\langtransporterte forurensninger\190246 Tålegrensekart Vestland\Data\Shape. You also find the shape files the same place. Note that what I have given as station code and station name is the name and code of the sub-catchment, as there is no station.

This is not a RESA/AM project. It uses data from different sources - some of the data are actually in RESA, but I extract everything from Vannmiljø, to get all available data in a region. So - I suppose we can just call it (almost) the same as in InstiPro, i.e. project_code = 190246, project_name = CL_Vestland

Let me know if you need more from me

3) For hydrology I think I have concluded just to use the information supplied with the regine units, i.e. 61-90 normal data. Partly because it is simple, but more importantly because they have estimated what they call tilsig, which takes into account all the moving of water between catchments due to hydropower (which is quite prominent in this region). I think this is more important than using recent data

4) Unfortunately I do not have the water chemistry data to fill in here yet, but I will fill it in as soon as I can

**Comment by kariaust** [comment]
To repeat - what I would like to do in this project is in short to calculate critical loads and exceedances for a range of sub-catchments (in six catchments), using dep data for 2012-2016 + 2030. For the draft report (due June 15th) I only need to present results for one catchment (Samnanger), so so far I have compiled data for this catchment only. Summarising the current status and what needs to be done, referring to the same points as above:

1. I need to calculate critical loads and exceedances based on the F factor model. So the script should be set up so that BC0_Ffac is used to calculate an F version of ANClimit, critical loads and exceedances. We then have three different versions of output, based on the three different BC0s. So either there must be a way to choose one or more, or the code produces all outputs, but it is clear which is which. In this project I will only use the F factor output (or, well, I consider also using the regression approach, but then with another, or various, regression equations, but I suppose there is no time for that now)

2. I have started to make an overview of the sub-catchments here: K:\Prosjekter\langtransporterte forurensninger\190246 Tålegrensekart Vestland\Data\Shape\Catchment info.xlsx. So far there is only input for one of the catchments, Samnanger. You find the shape files in the same folder. Note that what I have given as station code and station name is the name and code of the sub-catchment, as there is no station (at least no station for which the catchment is delineated). The coordinates are for the outlet, but I do not think you need those in this context? And you asked for project_code = 190246, project_name = CL_Vestland

3. Data for input_template_critical_loads_water.xlsx: Some of the input data would be easier to extract within the ‘system’, but I can also extract it externally, if time is limited (let me know quickly, so that I can work on this in parallel). These are the ones I would like to have but am still missing:
a. Nupt: Get N uptake from the BLR grid (CL database). If the sub-catchment is associated with different BLRs with different N uptake values, I think we should use the area-weighted average (or whatever that translates to in the raster world).
b. Lake_area: Calculate lake area per sub-catchment from the NVE_INNSJO map layer
c. Forest_area: Calculate forest area per sub-catchment from AR50
(Catch_area I have already entered, as I needed it to calculate the runoff. But in a more general setup this could be generated as well.)
Note that Samnanger_Tysseelva is not a true sub-catchment, it is just the part of the catchment furthest downstream. This means that **the data for Samnanger_Tysseelva for a, b and c should be generated for the whole catchment, i.e. the shape Samnanger.** The shape Samnanger_Tysseelva should only be used for the maps in the report

4. The excel template for Samnanger is here: K:\Prosjekter\langtransporterte forurensninger\190246 Tålegrensekart Vestland\Samnanger\input_template_critical_loads_water_Samnanger.xlsx. With the additional input from 3. above it should be possible to calculate critical loads.

5. Calculate exceedances using both 2012-2016 (new method, new grid) and 2030 (see Issue #4) as in 4. in 04_water_new_grid.ipynb. There should be only one exceedance value for each sub-catchment (and model/year). So if the deposition varies within the sub-catchment, an area-weighted average exceedance must be calculated (or whatever makes sense)
And: When calculating exceedances for Samnanger_Tysseelva the whole catchment must be used as basis. From 3. and 4. the calculated critical load is for the whole Samnanger catchment, so the deposition should also be for the whole catchment.

6. Outputs:
a. Table per catchment with absolute critical load (SSWC) and exceedances (SSWC and FAB, both time periods) for each sub-catchment (meq/m2/yr)
b. Maps of critical load (SSWC) and exceedance (again four types) for each catchment, showing the different sub-catchments
c. Potentially a nice actual map of the catchment, showing the sub-catchments, sampling points, lakes and main river network. Ideally the map should also show the hydropower tunnels given in the shape Vannkraft_Vannvei here: K:\Prosjekter\langtransporterte forurensninger\190246 Tålegrensekart Vestland\Data\Shape\NVE\NVEData\Vannkraft
These are the sampling points (in the map they need only to be numbered):

Vannlokalitet_kode | Vannlokalitet | UTM33 Ost (X) | UTM33 Nord (Y)
-- | -- | -- | --
055-58811 | Frølandselva, Samnanger 1 | -5621.3425 | 6728794.858
055-98152 | Frølandselva v/ trapp | -5194.7657 | 6728764.025
055-58813 | Tysselva, Samnanger 3 | -7750.7994 | 6728731.619
055-97626 | Storelva   Samnangervassdraget | -6148.8647 | 6729730.863
055-97634 | Fiskevatnet, utløp | -4943.6928 | 6733357.275

The maps could look something like the ones found here: K:\Prosjekter\langtransporterte forurensninger\190246 Tålegrensekart Vestland\Yndesdal\Kalkingsplan Yndesdal-Frøyset 2004.pdf
But again - if you have limited time now, I can also make Espen help me with the maps. Then let me know early on. But since these maps will have to be generated for five more catchments, it would be more efficient if you could set something up now, of course

**Comment by kariaust** [comment]
An update:
2. I made a change to one of the shapes. The ones to use are:
Samnanger
Samnanger_Frolandskanalen_ny
Samnanger_Frolandselva
Samnanger_Storelva
Samnanger_Tysseelva (you probably don't need this, as it is not used for the calculations, only the visualisation)
4. The excel template has been updated with the input from 3

**Comment by kariaust** [comment]
And sorry, just made another change to the template in 4

**Comment by JamesSample** [comment]
Closed by 5ab1abb907a8ca901bec98c2582a8f0b29b94f07
